In [25]:
import numpy as np

In [27]:
def elem_stiffness(E, A, n1, n2):
    #coordinates from nodes
    x1, y1 = n1
    x2, y2 = n2
    #distance calc
    L = np.sqrt((x2 - x1) ** 2 + (y2 - y1) ** 2)
    #local stiffness matrix
    k_local = (E * A / L) * np.array([[1, 0, -1, 0],
                                      [0,0,0,0],
                                       [-1, 0, 1, 0],
                                         [0,0,0,0]])
    #Global Stiffness
    #direction trig
    C = (x2 - x1) / L
    S = (y2 - y1) / L
    #transformation matrix
    b = np.array([[C, S, 0, 0],
                  [-S, C, 0, 0],
                  [0, 0, C, S],
                  [0, 0, -S, C]])
    #calc global stiffness
    k_global = b.T @ k_local @ b
    
    return k_local, k_global
    '''Suggestions for improvement:
    atan2
    allow for more flexible material properties
    '''
    
    
    

In [29]:
E = 29500000 
A = 0.1   
n1 = (0, 0)
n2 = (3, 4) 

k_local, k_global = elem_stiffness(E, A, n1, n2)

print("Local Stiffness Matrix:")
print(k_local)
print("\nGlobal Stiffness Matrix:")
print(k_global)

Local Stiffness Matrix:
[[ 590000.       0. -590000.       0.]
 [      0.       0.       0.       0.]
 [-590000.       0.  590000.       0.]
 [      0.       0.       0.       0.]]

Global Stiffness Matrix:
[[ 212400.  283200. -212400. -283200.]
 [ 283200.  377600. -283200. -377600.]
 [-212400. -283200.  212400.  283200.]
 [-283200. -377600.  283200.  377600.]]
