# ATHENA ZAPANTIS

import math as m
import numpy as np

class Truss:
    
    def __init__(self, nodes = [], material_properties = [], section_properties = []):
        '''Takes a list of vectors defining 
        the location of the nodes of the truss'''
        self.nodes = nodes
        self.material_properties =  material_properties
        self.section_properties = section_properties
        self.elements = []
    
    def calculate_element_length(self, node_index_1, node_index_2):
        return np.linalg.norm(nodes[node_index_1], nodes[node_index_2])
    
    def calculate_element_orientation(self, node_index_1, node_index_2)
        delta = np.array(nodes[node_index_1][0] - nodes[node_index_2][0], nodes[node_index_1][1] - nodes[node_index_2][1])
        return m.atan(delta[1], delta[0])
    
    def add_material_properties(self, material_properties):
        self.material_properties =  material_properties
        
    def add_section_properties(self, section_properties):
        ''''''
        self.section_properties = section_properties
        
    def add_element(self, element):
        '''element is a list of the form
        [node i, node j,  material property, section property]'''
        self.elements.append(element)

class Element(Truss):
    def calculate_element_local_stiffness_matrix(self, E, A, L):
        ke_local = np.zeros(4,4)
        ke_local[1, 1] = E * A / L 
        ke_local[1, 3] = -E * A / L
        ke_local[3, 1] = -E * A / L
        ke_local[3, 3] = E * A / L
        return ke_local
    
    def define_rotation_matrix(self, theta):
        unit_rotation = np.array(
            [(cos(theta), sin(theta)), 
             (-sin(theta), cos(theta))])
        return np.vstack((np.hstack((unit_rotation, np.zeros(2,2))), np.hstack((np.zeros(2,2), unit_rotation))))
    
    

nodes = [[0,0], [-10,-10], [10, -10]] # define [x,y] coordinates of each node
material_properties = [29000000, 10000, 15000000] # define E of steel, wood, carbon fiber
section_properties = [1, 10, 3.6] # define cross-sectional area

my_truss = Truss(nodes, material_properties, section_properties)
my_truss

# Scratch work is above

In [1]:
import math as m
import numpy as np

class Truss:
    
    def __init__(self, elements = []):
#         self.nodes = nodes
#         self.material_properties =  material_properties
#         self.section_properties = section_properties
        self.elements = elements
        self.nodes = set([])
        self.nodes.add(self.elements[element].node_i for element in self.elements)
        self.nodes.add(self.elements[element].node_j for element in self.elements)
    
#     def calculate_element_length(self, element_index):
#         return np.linalg.norm(self.elements[element_index][0], self.elements[element_index][1])
    
#     def calculate_element_orientation(self, node_index_1, node_index_2):
#         delta = np.array(nodes[node_index_1][0] - nodes[node_index_2][0], nodes[node_index_1][1] - nodes[node_index_2][1])
#         return m.atan2(delta[1], delta[0])
    
    def define_material_properties(self, material_properties):
        self.material_properties =  material_properties
        
    def define_section_properties(self, section_properties):
        self.section_properties = section_properties
        
    def add_element(self, element):
        '''accepts entries of the class Element'''
        self.elements.append(element)
        
    def get_material_properties(self):
        return self.material_properties
    
    def get_section_properties(self):
        return self.section_properties
    
    def get_nodes(self):
        print(self.nodes)
    
    def calculate_big_mac(self):
        '''calculates the total global stiffness matrix'''
        dof_i = []
        dof_j = []
        
#         for i in range(len(self.elements)): # NEED TO ITERATE THROUGH NODES, NOT ELEMENTS!
#             dof_i.append(2 * (i + 1) - 1)
#             dof_j.append(2 * (i + 1))
            
#         for node in range(len(self.elements))
            
        dimension = len(dof_i) + len(dof_j)
        
        k_global = np.zeros((dimension, dimension))
        ke_globals = [element.calculate_element_global_stiffness_matrix() for element in self.elements]
        
        
        
#         dof_i_count = 0
#         dof_j_count = 0
        
#         for matrix in ke_globals:
#             for row in matrix:
#                 for entry in row:
#                     k_global[dof_i_count][dof_j_count] += entry
#                     dof_j_count += 1
#                 dof_j_count == 0
#                 dof_i_count += 1
#             dof_i_count == 0
                    
        # yeah I definitely don't know how I want to iterate through this and add 
        # although I get what I'm supposed to do
        
        return k_global

In [2]:
class Element:
    
    def __init__(self, node_i = [0,0], node_j = [0,0], E = 0, A = 0):
        self.node_i = node_i
        self.node_j = node_j
        self.E = E
        self.A = A
        self.L = np.linalg.norm(np.array(self.node_i) - np.array(self.node_j))
    
    def calculate_element_local_stiffness_matrix(self):
        ke_local = np.zeros((4,4))
        stiffness = self.E * self.A / self.L
        ke_local[0, 0] = stiffness
        ke_local[0, 2] = -stiffness
        ke_local[2, 0] = -stiffness
        ke_local[2, 2] = stiffness
        return ke_local
    
    def define_rotation_matrix(self, theta):
        unit_rotation = np.array(
            [(m.cos(theta), m.sin(theta)), 
             (-m.sin(theta), m.cos(theta))])
        return np.vstack((
            np.hstack((unit_rotation, np.zeros((2, 2)))),
            np.hstack((np.zeros((2, 2)), unit_rotation))
        ))
    
    def calculate_element_length(self):
        self.L = np.linalg.norm(self.node_i, self.node_j)
        return self.L
    
    def calculate_element_orientation(self):
        delta = [self.node_i[0] - self.node_j[0], self.node_i[1] - self.node_j[1]]
        return m.atan2(delta[1], delta[0])
    
    def calculate_element_global_stiffness_matrix(self):
        theta = self.calculate_element_orientation()
        beta = self.define_rotation_matrix(theta)
        ke_local = self.calculate_element_local_stiffness_matrix()
        return beta.T @ ke_local @ beta

In [3]:
nodes = [[0,0], [-10,-10], [10, -10]] # define [x,y] coordinates of each node
material_properties = [29000000, 10000, 15000000] # define E of steel, wood, carbon fiber
section_properties = [1, 10, 3.6] # define cross-sectional area

element1 = Element(nodes[0], nodes[1], material_properties[0], section_properties[1])
element2 = Element(nodes[0], nodes[2], material_properties[2], section_properties[0])
element3 = Element(nodes[1], nodes[2], material_properties[1], section_properties[2])
elements = [element1, element2, element3]

my_truss = Truss(elements)

ke_local1 = element1.calculate_element_local_stiffness_matrix()
ke_local2 = element2.calculate_element_local_stiffness_matrix()
ke_local3 = element3.calculate_element_local_stiffness_matrix()
print(ke_local1, ke_local2, ke_local3)

ke_global1 = element1.calculate_element_global_stiffness_matrix()
ke_global2 = element2.calculate_element_global_stiffness_matrix()
ke_global3 = element3.calculate_element_global_stiffness_matrix()

print(ke_global1, ke_global2, ke_global3)

# k_global = my_truss.calculate_big_mac()

# print(k_global)

# my_truss.get_nodes()

[[ 20506096.65440988         0.         -20506096.65440988
          0.        ]
 [        0.                 0.                 0.
          0.        ]
 [-20506096.65440988         0.          20506096.65440988
          0.        ]
 [        0.                 0.                 0.
          0.        ]] [[ 1060660.17177982        0.         -1060660.17177982        0.        ]
 [       0.                0.                0.                0.        ]
 [-1060660.17177982        0.          1060660.17177982        0.        ]
 [       0.                0.                0.                0.        ]] [[ 1800.     0. -1800.     0.]
 [    0.     0.     0.     0.]
 [-1800.     0.  1800.     0.]
 [    0.     0.     0.     0.]]
[[ 10253048.32720494  10253048.32720494 -10253048.32720494
  -10253048.32720494]
 [ 10253048.32720494  10253048.32720494 -10253048.32720494
  -10253048.32720494]
 [-10253048.32720494 -10253048.32720494  10253048.32720494
   10253048.32720494]
 [-10253048.32720494 -